name: build docker and deploy to vps
on:
    push:
        branches:
            - main

jobs:
    Build-Deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PWD }}

            - name: Build
              run: docker build -t portfolio .

            - name: Tag
              run: docker tag portfolio:latest sarahkatz/portfolio:latest

            - name: Push
              run: docker push sarahkatz/portfolio:latest

            - name: Deploy
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USER }}
                password: ${{ secrets.VPS_PWD }}
                script: /home/debian/sh/ecf-deploy.sh